name: Python CI

# Trigger the workflow on push to the main branch or pull requests to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu machine to run the tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python environment
      with:
        python-version: '3.9'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install project dependencies

    - name: Run tests
      run: |
        pytest  # Run tests using pytest

    - name: Upload test results
      if: always()  # Upload test results regardless of success or failure
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: test-results  # Adjust if you have a specific path for test results

