name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  build:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Save Google Cloud credentials to a file
      run: |
        echo '${{ secrets.GCP_CREDENTIALS }}' > /tmp/key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/key.json" >> $GITHUB_ENV

    - name: Set environment variables
      run: |
        echo "GCP_DATASET_ID=${{ secrets.GCP_DATASET_ID }}" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/insight-hub:latest .

    - name: Push Docker image to Google Artifact Registry
      run: |
        gcloud auth configure-docker us-docker.pkg.dev
        docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/insight-hub:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy insight-hub \
          --image us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/insight-hub:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

