name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  build:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}


    - name: Build Docker image
      run: |
        docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/insight-hub/insight-hub:latest .

    - name: Push Docker image to Google Artifact Registry
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev
        docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/insight-hub/insight-hub:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy insight-hub \
          --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/insight-hub/insight-hub:latest \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated
