name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  build:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}  # Your GCP project ID
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # Path to service account key in GitHub secrets
    
    - name: Configure Docker for Google Cloud
      run: |
        gcloud auth configure-docker us-docker.pkg.dev  # For Artifact Registry
        # If using GCR, replace with:
        # gcloud auth configure-docker gcr.io
    
    - name: Build Docker image
      run: |
        docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/insight-hub:latest .
        # If using GCR, replace with:
        # docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/insight-hub:latest .
    
    - name: Push Docker image to Google Artifact Registry
      run: |
        docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/insight-hub:latest
        # If using GCR, replace with:
        # docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/insight-hub:latest
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy insight-hub \
          --image us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/insight-hub:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
        # If using GCR, replace with:
        # gcloud run deploy insight-hub \
        #   --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/insight-hub:latest \
        #   --platform managed \
        #   --region us-central1 \
        #   --allow-unauthenticated

