name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  build:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}  # Your GCP project ID
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # Path to service account key in GitHub secrets
    
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/insight-hub .
    
    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/insight-hub
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy insight-hub \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/insight-hub \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

